### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by nickcat5** [Rexcantor/MultiLanguagePlugin#10]
The Plugin isnt working at all.

**Comment by Rexcantor** [comment]
I contacted you through Discord.
In case you didn't see, this is the message I send you:

> I'll need you to do the following:
• Send me the config and language files of MLP
• Send me the config (and language file - if it's outside the config) of the plugin you're trying to translate.
• If there is any error on console, please send them to me too
• Send me screenshots of what's wrong in-game  
Thanks,
Rexcantor64

And please describe your problem. "isn't working" doesn't help at all.
