### ISSUE TITLE
Just bought the plugin and can't use it because it doesn't work with 1.12 :(

### ISSUE THREAD

**Issue by Fonzee9** [Rexcantor/MultiLanguagePlugin#12]
Chat and title replacement have been disabled. Only the API should work at this time. Please tell @Rexcantor64 to add support to v1_12_R1

**Comment by Rexcantor** [comment]
I completely forgot that I had to update the plugin. I'll release an update today to fix it.

**Comment by Fonzee9** [comment]
Also this plugin does a lot of languages right? Like translates because in /Language gui or whatever it is it only shows 2 languages..

**Comment by Rexcantor** [comment]
Yeah, it supports up to 54 languages if I remember correctly. But I'll add support for infinite languages on this update.

**Comment by Fonzee9** [comment]
Okay thanks also if a player joins and there mc language is set to lets say Spanish will it auto translate for them or will they have to use /language?

**Comment by Rexcantor** [comment]
The plugin SHOULD recognise the player's mc language and set their language in game, although some people reported that this isn't working.

**Comment by Fonzee9** [comment]
But have you tested it and does it work for you? 👍

**Comment by Rexcantor** [comment]
Unfortunately, I don't have time to test it today, but I managed to update the plugin to 1.12.

The update is available on the plugin page or thought [here](https://www.spigotmc.org/resources/multilanguageplugin-9.30331/update?update=168559).  
If you find any bug, please open another issue here on GitHub.
