### ISSUE TITLE
Language Auto-Detection

### ISSUE THREAD

**Issue by Rexcantor** [Rexcantor/MultiLanguagePlugin#15]
The language auto-detection system is not working at the moment. This happens due to a delay on the client, meaning the server only knows the language the player is using a few seconds after joining. As MLP gets the language right when the player joins, it always gets the default language (en_us).

**Comment by DynamicThijs** [comment]
Can't you set it to en_US right on join, then get the Minecraft language of the player after a few seconds and change it? Then remember the language and use that right on join. (and still check every join)

**Comment by masterdoctor** [comment]
@DynamicThijs That's exactly what I've just done :)

**Comment by masterdoctor** [comment]
This bug is fixed and will be live in the next version.
