### ISSUE TITLE
IllegalPluginAccessException

### ISSUE THREAD

**Issue by DynamicThijs** [Rexcantor/MultiLanguagePlugin#17]
Hello there, I'm always getting the following error message when my server stops:
https://gist.github.com/DynamicThijs/b0ea41a24fd7189699d0b70c94f6ea73

Can you fix that?

**Comment by masterdoctor** [comment]
I'll take a look. Thank you.

**Comment by Rexcantor** [comment]
@DynamicThijs The bug is already fixed and will be live on the next version.
