### ISSUE TITLE
[BUG] When colors code are together with a placeholder (%1)

### ISSUE THREAD

**Issue by 0rangeFox** [Rexcantor/MultiLanguagePlugin#23]
### Server info:

**MLP version:** 0.6.2
**Minecraft version (the MC version of your server software):** 1.8.8
**Server software:** Spigot
**Using BungeeCord (if you use a fork, please specify):** Yes (Travertine)

### Problem info:

**Issue type:** Bug report
#### Description:
When a colour code is next to a placeholder it does not work the way he should. But when seperated it works just fine!

### Error logs (in case it's a bug report):
Some prints:
[Print #1](http://prntscr.com/j3h7wc) (Color code together with the placeholder)
[Print #2](http://prntscr.com/j3h91i) (Color code seperated with the placeholder)

**Comment by Rexcantor** [comment]
Try to enable `use-new-chat-parser` in config. I'll fix it in the old parser anyway.

**Comment by 0rangeFox** [comment]
The problem was solved, by enabling `use-new-chat-parser`. Thank you.

**Comment by Rexcantor** [comment]
The old chat parser is deprecated, so I won't be providing support for it.
