### ISSUE TITLE
Not clickable link

### ISSUE THREAD

**Issue by download042** [Rexcantor/MultiLanguagePlugin#25]
pre. 0.6.3 MLP
  
1.11.2
Spigot

Yup, bungeecord

Bug report

The link sended by MLP is not clickable in the chat.

Error log:
https://pastebin.com/nwE091PA

**Comment by Rexcantor** [comment]
Can you please provide the full message, so I can test locally?

**Comment by Rexcantor** [comment]
Fixed. Will be available on 0.6.3.
