### ISSUE TITLE
Multi pages GUI support

### ISSUE THREAD

**Issue by Rexcantor** [Rexcantor/MultiLanguagePlugin#4]
Add support for infinite languages adding support for multiple pages on the language selection GUI.

**Comment by Rexcantor** [comment]
Added on [0.3.0](https://www.spigotmc.org/resources/multilanguageplugin-9.30331/update?update=168559)!

Thanks, @masterdoctor for providing the code!

**Comment by masterdoctor** [comment]
No problem rexy!
